apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: prefect
  name: mem-cpu-quota
spec:
  hard:
    requests.cpu: "2000M"
    limits.cpu: "2500m"
    requests.memory: 1050Mi
    limits.memory: 1200Mi
